# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Launcher.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Launcher(object):
    def setupUi(self, Launcher):
        Launcher.setObjectName("Launcher")
        Launcher.resize(1000, 618)
        self.gridLayout = QtWidgets.QGridLayout(Launcher)
        self.gridLayout.setObjectName("gridLayout")
        self.le_username = QtWidgets.QLineEdit(Launcher)
        self.le_username.setObjectName("le_username")
        self.gridLayout.addWidget(self.le_username, 0, 0, 1, 1)
        self.pb_startgame = QtWidgets.QPushButton(Launcher)
        self.pb_startgame.setObjectName("pb_startgame")
        self.gridLayout.addWidget(self.pb_startgame, 1, 0, 1, 1)

        self.retranslateUi(Launcher)
        QtCore.QMetaObject.connectSlotsByName(Launcher)

    def retranslateUi(self, Launcher):
        _translate = QtCore.QCoreApplication.translate
        Launcher.setWindowTitle(_translate("Launcher", "Launcher"))
        self.le_username.setPlaceholderText(_translate("Launcher", "用户名"))
        self.pb_startgame.setText(_translate("Launcher", "开始游戏"))
